---
title: "Growth rates of PIT data from the Delaware River"
author: "Ben Letcher"
date: '`r Sys.Date()`'
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")

library(tidyverse)
library(lubridate)
library(knitr)
library(targets)
library(tarchetypes)
library(MCMCvis)
library(htmltools)

library(bs4Dash)
library(DT)
library(gt)
library(pingr)
library(shinybusy)
library(shinyWidgets)

options(tinytex.verbose = TRUE)
```

```{r}
d <- tar_read(target_d)
eh <- tar_read(target_eh)
```

Add growth rate
```{r}

d <- d %>%
  mutate(year = as.numeric(substr(dateYM, 1,4)),
         month = as.numeric(substr(dateYM, 6,7)))

d <- d %>%
  group_by(tag) %>%
  arrange(tag, date) %>%
  mutate(LengthLag = lag(Length),
         dateLag = lag(date),
         dateDiff = as.numeric(date - dateLag),
         growth = (Length - LengthLag) / dateDiff)
  
```

```{r}
meanGrowth <- d %>%
  filter(dateDiff < 300, growth > 0, growth < 3) %>%
  group_by(mainTrib, year, month, sizeState) %>%
  summarise(mean = mean(growth, na.rm = TRUE),
            n = n()) %>%
  filter(n > 3)

ggplot(meanGrowth, aes(month, mean, color = factor(mainTrib))) +
  geom_point(aes(size = n)) +
  geom_line() +
  ylim(-0.3, 0.4) +
  facet_grid(sizeState ~ year)

ggplot(meanGrowth, aes(month, mean, color = factor(year))) +
  geom_point(aes(size = n)) +
  geom_line() +
  ylim(-0.3, 0.4) +
  facet_grid(sizeState ~ mainTrib)

ggplot(meanGrowth, aes(sizeState, mean, color = factor(mainTrib))) +
  geom_point(aes(size = n)) +
  geom_line() +
  ylim(-0.3, 0.4) +
  facet_grid(month ~ year)
  
```

```{r}
meanGrowthSize <- d %>%
  filter(dateDiff < 300, growth > 0, growth < 3) %>%
  group_by(mainTrib, sizeState) %>%
  summarise(mean = mean(growth, na.rm = TRUE),
            sd = sd(growth, na.rm = TRUE),
            n = n()) %>%
  filter(n > 5)


ggplot(meanGrowthSize, aes(sizeState, mean, color = factor(mainTrib))) +
  geom_point(aes(size = n)) +
  ylab("Mean growth (mm/d)") +
  ylim(0, 0.4) +
  geom_line()
```

```{r}
meanGrowthSizeYear <- d %>%
  filter(dateDiff < 300, growth > 0, growth < 3) %>%
  group_by(mainTrib, sizeState, year) %>%
  summarise(mean = mean(growth, na.rm = TRUE),
            sd = sd(growth, na.rm = TRUE),
            n = n()) %>%
  filter(n > 5)



ggplot(meanGrowthSizeYear %>% filter(year == 2019, n > 20), aes(sizeState, mean, color = factor(mainTrib))) +
  geom_point(aes(size = n)) +
  ylab("Mean growth (mm/d)") +
  #ylim(0, 0.4) +
  geom_line() +
  facet_wrap(~year)

tmp <- d%>% filter(year ==  2020, mainTrib == "main", sizeState == 2)
table(tmp$growth)
```


